$in_tile = self.tiles[0];
$c = $in_tile.coord;
$out_tile = tile[$c.x, $c.y + 1, $c.z];

if self.property["open"] == false then
  set_entity_property(self, "open", true);
  play_animation(self, "open");
  modify_navigation($out_tile, $in_tile, WALK_AND_INTERACT);
else
  set_entity_property(self, "open", false);
  play_animation(self, "close");
  modify_navigation($out_tile, $in_tile, INTERACT_ONLY);
end;
